create_clock -period 10.000 -name clk_in -waveform {0.000 5.000} [get_ports clk_in]

set_property PACKAGE_PIN W5 [get_ports clk_in]
set_property PACKAGE_PIN W6 [get_ports dcm_locked]
set_property PACKAGE_PIN W7 [get_ports {sin_out[0]}]
set_property PACKAGE_PIN T2 [get_ports {sin_out[4]}]
set_property PACKAGE_PIN V3 [get_ports {cos_out[5]}]
set_property PACKAGE_PIN U4 [get_ports {sin_out[2]}]
set_property PACKAGE_PIN R2 [get_ports {sin_out[5]}]
set_property PACKAGE_PIN W3 [get_ports {cos_out[4]}]
set_property PACKAGE_PIN W4 [get_ports {sin_out[1]}]
set_property PACKAGE_PIN U2 [get_ports {cos_out[6]}]
set_property PACKAGE_PIN T1 [get_ports {cos_out[1]}]
set_property PACKAGE_PIN V4 [get_ports {sin_out[3]}]
set_property PACKAGE_PIN U3 [get_ports {cos_out[7]}]
set_property PACKAGE_PIN T3 [get_ports {sin_out[6]}]
set_property PACKAGE_PIN V2 [get_ports {cos_out[3]}]
set_property PACKAGE_PIN W2 [get_ports {cos_out[2]}]
set_property PACKAGE_PIN R3 [get_ports {sin_out[7]}]
set_property PACKAGE_PIN U1 [get_ports {cos_out[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports clk_in]
set_property IOSTANDARD LVCMOS18 [get_ports dcm_locked]

set_property IOSTANDARD LVCMOS18 [get_ports sin_out[*]]
set_property IOSTANDARD LVCMOS18 [get_ports cos_out[*]]
