create_clock -period 10.000 -name clk_in -waveform {0.000 5.000} [get_ports clk_in]

set_property PACKAGE_PIN W5 [get_ports clk_in]
set_property PACKAGE_PIN W6 [get_ports dcm_locked]
set_property PACKAGE_PIN W7 [get_ports {sin_out[0]}]
set_property PACKAGE_PIN T2 [get_ports {sin_out[4]}]
set_property PACKAGE_PIN V3 [get_ports {cos_out[5]}]
set_property PACKAGE_PIN U4 [get_ports {sin_out[2]}]
set_property PACKAGE_PIN R2 [get_ports {sin_out[5]}]
set_property PACKAGE_PIN W3 [get_ports {cos_out[4]}]
set_property PACKAGE_PIN W4 [get_ports {sin_out[1]}]
set_property PACKAGE_PIN U2 [get_ports {cos_out[6]}]
set_property PACKAGE_PIN T1 [get_ports {cos_out[1]}]
set_property PACKAGE_PIN V4 [get_ports {sin_out[3]}]
set_property PACKAGE_PIN U3 [get_ports {cos_out[7]}]
set_property PACKAGE_PIN T3 [get_ports {sin_out[6]}]
set_property PACKAGE_PIN V2 [get_ports {cos_out[3]}]
set_property PACKAGE_PIN W2 [get_ports {cos_out[2]}]
set_property PACKAGE_PIN R3 [get_ports {sin_out[7]}]
set_property PACKAGE_PIN U1 [get_ports {cos_out[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports clk_in]
set_property IOSTANDARD LVCMOS18 [get_ports dcm_locked]

set_property IOSTANDARD LVCMOS18 [get_ports sin_out[*]]
set_property IOSTANDARD LVCMOS18 [get_ports cos_out[*]]

set_property PACKAGE_PIN L2 [get_ports {q[13]}]
set_property PACKAGE_PIN J2 [get_ports {q[9]}]
set_property PACKAGE_PIN M1 [get_ports {q[2]}]
set_property PACKAGE_PIN L1 [get_ports {q[15]}]
set_property PACKAGE_PIN M3 [get_ports {q[4]}]
set_property PACKAGE_PIN J3 [get_ports {q[5]}]
set_property PACKAGE_PIN K3 [get_ports {q[6]}]
set_property PACKAGE_PIN H1 [get_ports {q[12]}]
set_property PACKAGE_PIN J1 [get_ports {q[11]}]
set_property PACKAGE_PIN M2 [get_ports {q[1]}]
set_property PACKAGE_PIN K2 [get_ports {q[14]}]
set_property PACKAGE_PIN G3 [get_ports {q[8]}]
set_property PACKAGE_PIN G2 [get_ports {q[7]}]
set_property PACKAGE_PIN L3 [get_ports {q[3]}]
set_property PACKAGE_PIN H2 [get_ports {q[10]}]
set_property PACKAGE_PIN N1 [get_ports {q[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {q[*]}]
